/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AppSettingsIndexImport } from './routes/_app/settings/index'
import { Route as AppReactflowIndexImport } from './routes/_app/reactflow/index'
import { Route as AppMermaidIndexImport } from './routes/_app/mermaid/index'
import { Route as AppMarkdownIndexImport } from './routes/_app/markdown/index'
import { Route as AppHomeIndexImport } from './routes/_app/home/index'
import { Route as AppDashboardMonitorIndexImport } from './routes/_app/dashboard/monitor/index'
import { Route as AppDashboardConsoleIndexImport } from './routes/_app/dashboard/console/index'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppSettingsIndexRoute = AppSettingsIndexImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)

const AppReactflowIndexRoute = AppReactflowIndexImport.update({
  id: '/reactflow/',
  path: '/reactflow/',
  getParentRoute: () => AppRoute,
} as any)

const AppMermaidIndexRoute = AppMermaidIndexImport.update({
  id: '/mermaid/',
  path: '/mermaid/',
  getParentRoute: () => AppRoute,
} as any)

const AppMarkdownIndexRoute = AppMarkdownIndexImport.update({
  id: '/markdown/',
  path: '/markdown/',
  getParentRoute: () => AppRoute,
} as any)

const AppHomeIndexRoute = AppHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardMonitorIndexRoute = AppDashboardMonitorIndexImport.update({
  id: '/dashboard/monitor/',
  path: '/dashboard/monitor/',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardConsoleIndexRoute = AppDashboardConsoleIndexImport.update({
  id: '/dashboard/console/',
  path: '/dashboard/console/',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/home/': {
      id: '/_app/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/markdown/': {
      id: '/_app/markdown/'
      path: '/markdown'
      fullPath: '/markdown'
      preLoaderRoute: typeof AppMarkdownIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/mermaid/': {
      id: '/_app/mermaid/'
      path: '/mermaid'
      fullPath: '/mermaid'
      preLoaderRoute: typeof AppMermaidIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/reactflow/': {
      id: '/_app/reactflow/'
      path: '/reactflow'
      fullPath: '/reactflow'
      preLoaderRoute: typeof AppReactflowIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/console/': {
      id: '/_app/dashboard/console/'
      path: '/dashboard/console'
      fullPath: '/dashboard/console'
      preLoaderRoute: typeof AppDashboardConsoleIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/monitor/': {
      id: '/_app/dashboard/monitor/'
      path: '/dashboard/monitor'
      fullPath: '/dashboard/monitor'
      preLoaderRoute: typeof AppDashboardMonitorIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppHomeIndexRoute: typeof AppHomeIndexRoute
  AppMarkdownIndexRoute: typeof AppMarkdownIndexRoute
  AppMermaidIndexRoute: typeof AppMermaidIndexRoute
  AppReactflowIndexRoute: typeof AppReactflowIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppDashboardConsoleIndexRoute: typeof AppDashboardConsoleIndexRoute
  AppDashboardMonitorIndexRoute: typeof AppDashboardMonitorIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppHomeIndexRoute: AppHomeIndexRoute,
  AppMarkdownIndexRoute: AppMarkdownIndexRoute,
  AppMermaidIndexRoute: AppMermaidIndexRoute,
  AppReactflowIndexRoute: AppReactflowIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppDashboardConsoleIndexRoute: AppDashboardConsoleIndexRoute,
  AppDashboardMonitorIndexRoute: AppDashboardMonitorIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AppIndexRoute
  '/home': typeof AppHomeIndexRoute
  '/markdown': typeof AppMarkdownIndexRoute
  '/mermaid': typeof AppMermaidIndexRoute
  '/reactflow': typeof AppReactflowIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/dashboard/console': typeof AppDashboardConsoleIndexRoute
  '/dashboard/monitor': typeof AppDashboardMonitorIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AppIndexRoute
  '/home': typeof AppHomeIndexRoute
  '/markdown': typeof AppMarkdownIndexRoute
  '/mermaid': typeof AppMermaidIndexRoute
  '/reactflow': typeof AppReactflowIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/dashboard/console': typeof AppDashboardConsoleIndexRoute
  '/dashboard/monitor': typeof AppDashboardMonitorIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/home/': typeof AppHomeIndexRoute
  '/_app/markdown/': typeof AppMarkdownIndexRoute
  '/_app/mermaid/': typeof AppMermaidIndexRoute
  '/_app/reactflow/': typeof AppReactflowIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/dashboard/console/': typeof AppDashboardConsoleIndexRoute
  '/_app/dashboard/monitor/': typeof AppDashboardMonitorIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/register'
    | '/'
    | '/home'
    | '/markdown'
    | '/mermaid'
    | '/reactflow'
    | '/settings'
    | '/dashboard/console'
    | '/dashboard/monitor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/home'
    | '/markdown'
    | '/mermaid'
    | '/reactflow'
    | '/settings'
    | '/dashboard/console'
    | '/dashboard/monitor'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/'
    | '/_app/home/'
    | '/_app/markdown/'
    | '/_app/mermaid/'
    | '/_app/reactflow/'
    | '/_app/settings/'
    | '/_app/dashboard/console/'
    | '/_app/dashboard/monitor/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/login",
        "/register"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/",
        "/_app/home/",
        "/_app/markdown/",
        "/_app/mermaid/",
        "/_app/reactflow/",
        "/_app/settings/",
        "/_app/dashboard/console/",
        "/_app/dashboard/monitor/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/home/": {
      "filePath": "_app/home/index.tsx",
      "parent": "/_app"
    },
    "/_app/markdown/": {
      "filePath": "_app/markdown/index.tsx",
      "parent": "/_app"
    },
    "/_app/mermaid/": {
      "filePath": "_app/mermaid/index.tsx",
      "parent": "/_app"
    },
    "/_app/reactflow/": {
      "filePath": "_app/reactflow/index.tsx",
      "parent": "/_app"
    },
    "/_app/settings/": {
      "filePath": "_app/settings/index.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/console/": {
      "filePath": "_app/dashboard/console/index.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/monitor/": {
      "filePath": "_app/dashboard/monitor/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
